# Site settings
title: Тёмно Зелёный Джаз
tagline: Здесь могла быть ваша реклама
email: site@darkgreen.ru
description: > # this means to ignore newlines until "baseurl:"
  Место для лытдыбра, на который можно дать ссылку.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.darkgreen.ru" # the base hostname & protocol for your site
github_username:  nikolay-bukharev

exclude: ["Gemfile", "Gemfile.lock", "CNAME"]

# Build settings
markdown: kramdown
